/*
 * Drive times shown on the site: Mapbox Directions ETAs (driving, typical traffic) from each venue
 * to each key location, in whole minutes. Generated by `npm run routes`; see location-map.ts.
 */
import data from './drive-times.json';
import type { DriveTimes, KeyLocationId } from './types';

export const driveTimes = data as DriveTimes;

/** "12 minutes", as the marker cards and route rows print it. */
export const driveTime = (venue: string, place: KeyLocationId) => {
  const minutes = driveTimes[venue]?.[place];
  return minutes === undefined ? '' : `${minutes} ${minutes === 1 ? 'minute' : 'minutes'}`;
};
