/*
 * Drive times shown on the site, in whole minutes: Mapbox Directions ETAs (driving, typical
 * traffic) from each venue to each key location, generated by `npm run routes` (see
 * location-map.ts), with the client's own figures taking precedence where given.
 */
import data from './drive-times.json';
import type { DriveTimes, KeyLocationId } from './types';

/** The client's figures for the venue pages (October 2026): one list for both Al Quoz venues. */
const alQuoz = { dubaiHills: 7, mallOfTheEmirates: 12, businessBay: 10, jumeirahRoad: 12, dubaiMall: 15 };
const clientTimes: DriveTimes = { 'fintech-district': alQuoz, 'creative-park': alQuoz };

export const driveTimes: DriveTimes = Object.fromEntries(
  Object.entries(data as DriveTimes).map(([venue, times]) => [venue, { ...times, ...clientTimes[venue] }])
);

/** "12 minutes", as the marker cards and route rows print it. */
export const driveTime = (venue: string, place: KeyLocationId) => {
  const minutes = driveTimes[venue]?.[place];
  return minutes === undefined ? '' : `${minutes} ${minutes === 1 ? 'minute' : 'minutes'}`;
};
